### ISSUE TITLE
Persistent header

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#11]
@MortenHofft would it be posible to have a persistent header while scrolling down as the one GBIF page has?

<img width="1411" alt="Captura de Pantalla 2021-03-17 a la(s) 3 55 16 p  m" src="https://user-images.githubusercontent.com/5700527/111537427-6c03b500-8739-11eb-9b46-802ea0d859dc.png">

**Comment by MortenHofft** [comment]
I'm afraid the theme does not support it no. I decided not to as they are more cumbersome to implement and come with a slew of other issues/tasks I find. So in the interest of keeping the project as simple as possible I decided not to.

**Comment by camiplata** [comment]
Let's keep it simple then.

Thanks!
