### ISSUE TITLE
data exploration | what is the lock for?

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#18]
<img width="401" alt="Captura de Pantalla 2021-05-01 a la(s) 9 39 36 a  m" src="https://user-images.githubusercontent.com/5700527/116785830-37d22280-aa61-11eb-86b2-12c402cac390.png">

**Comment by MortenHofft** [comment]
For locking first column in place for horizontal scroll. But currently there is so few columns added that it has no effect on most screen sizes
