### ISSUE TITLE
translated versions

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-colombian-biodiversity#2]
Hi @verovanporras 
I notice that 4 of the news pages have the same `lang-ref` value.
https://github.com/gbif/hp-colombian-biodiversity/blame/master/_posts/2021-01-29-reto_ebbe_nielsen_2021.md#L5

The `lang-ref` is the id of the translation version (so if 2 or more pages have the same lang-ref, then they are considered different translations of the same content). If you do not aim for a multilingual site you do not need it. But if you add it, then they need to be different in this case. Else the page will show as being available in 4 different spanish versions (as you can see in the language switcher)

Let me know if you need any help.
I will add a section on translations to the documentation

**Comment by camiplata** [comment]
@MortenHofft Thanks for noticing, we where unaware of the use of `lang-ref` 

@RicardoOrtizG @EstebanMH-SiB Please also check this for the sections you have created.

**Comment by camiplata** [comment]
I just removed all the lang-ref values from the post, for the moment we wont have this content translated
