### ISSUE TITLE
Danish/english translation

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-colombian-biodiversity#22]
I notice that you have english in the menu with available translations. But that it takes you to a danish stub.
Do you plan to translate the site into english? If not, then let me know if you need help in removing the (danish) translation.

**Comment by camiplata** [comment]
Hi @MortenHofft we were aiming to have a landing page in english, but that will take more time so we prefer -at least for now- to have the portal only in spanish. For this I removed  "en" from _data/languages.yml and  _config.yml. But I get the following behavior:

<img width="503" alt="Captura de Pantalla 2021-09-23 a la(s) 5 26 54 p  m" src="https://user-images.githubusercontent.com/5700527/134592124-5f5d0e4e-9ccd-480c-86a9-31ccf157f99b.png">
<img width="562" alt="Captura de Pantalla 2021-09-23 a la(s) 5 27 08 p  m" src="https://user-images.githubusercontent.com/5700527/134592148-fd58490b-1d62-488f-aa09-3a0137188401.png">

Then, yes please let me know how can I remove this doble "Español" option, I didn't want to remove the files of the "en" folder as we will eventually translate part of the portal to English.

**Comment by MortenHofft** [comment]
yes, sorry. I never got around to finishing that. When building the site all markdown files with frontmatter will result in an html page. Including all the files in the `en` folder. And those are stating that they are a copy of the spanish content (using the `lang-ref` attribute). So the 4 pages that existed in the `en` folder appears as translated. 
We can choose between adding a list of excluded files using `_config.yml` or simply deleting the content we do not want. I opted for the later.

**Comment by camiplata** [comment]
I see, thanks for fixing the bug
