### ISSUE TITLE
data scope | country:CO and publishingCountry:CO

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#25]
@timrobertson100 is posible to have a data scope that has both data about colombia and published from colombia? I tried doing this combinantiond but did not succed and I also see tha on gbif.org it is not posible to have both options.

**Comment by MattBlissett** [comment]
GBIF.org is more restrictive than the hosted portals.  I've extended the scope to Colombia + Published by Colombia.

**Comment by camiplata** [comment]
Thanks @MattBlissett
