### ISSUE TITLE
DNS adjustment

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#26]
Hi @MattBlissett, we  followed the instructions at https://github.com/gbif/hosted-portals/blob/main/getting-started/domain-name.md#subdomains-datatecalazz-etc, could you please update GBIF's configuration to use the domain.

We will be using biodiversidad.co

**Comment by MattBlissett** [comment]
Hi,

This is now set up.  https://biodiversidad.co redirects to https://sibcolombia.net/ as it did before, but this is now done on GBIF's server.
