### ISSUE TITLE
beta version

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-colombian-biodiversity#28]
I love the touch of adding a red dot with "version beta"!

On mobile it doesn't show as nice, perhaps it is easier to control if you add some markup instead of relying on the pseudo selectors? I just wanted to let you know that it is possible to do:

```yml
- text: <span class="version-beta"><span>Versión Beta</span></span>
```
https://github.com/gbif/hp-colombian-biodiversity/blob/master/_data/navigation.yml#L81

**Comment by camiplata** [comment]
@aduarte-sib intentemos poner de nuevo el ajuste en el logo y removemos el boton

**Comment by camiplata** [comment]
beta version has been removed
