### ISSUE TITLE
How to hide pages

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#30]
Is there any possibility to have some pages deployed for the staging environment but not for production?

For example, we are creating [this page ](https://hp-colombian-biodiversity.gbif-staging.org/compartir/prueba_dwc)and it will take us a while to finish it, we want to keep seeing the progress of it on staging, nevertheless currently even if it is 'hidden' it is been created and will be indexed but search engines. Is there a way to hide it for production, something similar to a gitignore but only for the production environment?

**Comment by MortenHofft** [comment]
We do not generate a sitemap, so it is unlikely to be indexed unless someone/some page links to it.

But you can set the frontmatter to `published: false`
https://jekyllrb.com/docs/front-matter/

When building to staging we include those (staging asks robots not to index be indexed), but exclude unpublished in production.
