### ISSUE TITLE
Missing Data scope

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#31]
@MortenHofft  Yesterday we noticed https://biodiversidad.co/data data scope changed, now the portal shows all GBIF data an the page isnot showing the filter customization made by us.

<img width="1299" alt="Captura de Pantalla 2022-01-14 a la(s) 7 56 19 a  m" src="https://user-images.githubusercontent.com/5700527/149518876-ed97e9f1-9962-42d8-810d-dc231758abd0.png">

**Comment by MortenHofft** [comment]
That is no good. I will look now.

**Comment by MortenHofft** [comment]
You have done multiple commits since. Can it go to production? If so you should do a release to get it fixed.

**Comment by MortenHofft** [comment]
I've created a new release based on the previous one. It is now fixed in production. Whatever changes you have done since yesterday has not been included.

**Comment by camiplata** [comment]
Thank for your super fast response!!!
