### ISSUE TITLE
aditional redirections to biodiversidad.co

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#33]
Hi @MattBlissett, 

We want to redirect our older portals (https://datos.biodiversidad.co/ and https://coleciones.biodiversidad.co/) to biodiversidad.co., we plan to do so by following [the instructions](https://github.com/gbif/hosted-portals/blob/main/getting-started/domain-name.md#subdomains-datatecalazz-etc) you gave us some months ago. Is this the right path? 

@daiesco

**Comment by MattBlissett** [comment]
Hi,

Yes, if you set the DNS for datos.biodiversidad.co and coleciones.biodiversidad.co to hosted-portal.gbif.org, the same as you have for www.biodiversidad.co, then I can set up the redirect.

It would work the same as www.biodiversidad.co → biodiversidad.co.

**Comment by camiplata** [comment]
We are ready! @MattBlissett you can do your magic and set up the redirect!

**Comment by MattBlissett** [comment]
Hi,

These are both ready and working, thanks.

**Comment by camiplata** [comment]
Great Matt!  this helps us a lot
