### ISSUE TITLE
Help setting the domain biodiversidad.co for a new tool

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/hp-colombian-biodiversity#34]
Hi @MattBlissett 

We need your help to set a domain for a new tool. We developed a tool that generates publication certifies for legal proposes, this tool is allocated in one of our servers and we want the tool to have this domain: [biodiversidad.co/certificados/publicacion-permisos](http://biodiversidad.co/certificados/publicacion-permisos). 

So, we need to redirect this IP [http://51.38.48.143:4000/login/](http://51.38.48.143:4000/certifies/) to the direction I mentioned above. Also, the contractor leading this task asked me to set the location using this location rule if you use nginx:

 /permisos{
    location /certificados/publicacion-permisos{
    proxy_pass http://51.38.48.143:4000/
  } 

I don't understand if this [instructions](https://github.com/gbif/hosted-portals/blob/main/getting-started/domain-name.md#subdomains-datatecalazz-etc) fits this case, or if an additional step is necessary. 

Thanks in advance.

**Comment by MattBlissett** [comment]
Hi,

I will need to ask for our firewall to be updated, as we don't have outbound port 4000 access by default.

Is this something you'd want for biodiversidad.co, or the test hp-colombian-biodiversity.gbif-staging.org too?

**Comment by RicardoOrtizG** [comment]
Hi, 

Thanks for the swift answer. It's only for biodiversidad.co

**Comment by RicardoOrtizG** [comment]
Hi Matt, I'm wondering if you were able to get the authorization for the firewall update, or if there is anything else that we have to do from our side.
