### ISSUE TITLE
broken image /recursos/ipt

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-colombian-biodiversity#35]
https://biodiversidad.co/recursos/ipt the header image isn't showing

**Comment by MortenHofft** [comment]
The issue seem to be that the image is an image from the GBIF image API. Please use the original image instead.

**Comment by camiplata** [comment]
Fixed [f3c2704](https://github.com/gbif/hp-colombian-biodiversity/commit/f3c27043da571f7593e1f8ece45805a59733ae6d)
