### ISSUE TITLE
Two more new redirections  and help with old ones 😬

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#37]
Hi @MattBlissett, here we are again tidying up our virtual home.

We kindly ask you to help us to redirect the following urls to biodiversidad.co, we already set the DNS.

1. https://listas.biodiversidad.co/ to biodiversidad.co
2. https://tools.sibcolombia.net/procesador-cr-sib/ to https://biodiversidad.co/compartir/guia-para-reportar/

We also noticed that the redirection #34 was fixed after yesterday issue, but #33 are still broken (https://datos.biodiversidad.co/ and https://coleciones.biodiversidad.co/).

Thank you in advance for your help

**Comment by MattBlissett** [comment]
Hi,

I've added the redirects.

I saw something strange with https://datos.biodiversidad.co/, the old site seemed to be cached in my browser. I cleared my browser cache and it works now, but since I've cleared the cache I can't see what was there before.

**Comment by camiplata** [comment]
All url's are working , Thank you
