### ISSUE TITLE
Dark theme in our hosted portal

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/hp-colombian-biodiversity#38]
Hi,

We should like to know if the [dark theme](https://hp-demo-nhc-dark.gbif-staging.org/) can be already implemented and how we can do it, we cheked that site and the documentation but it does not have information of how to do it.

Also we would like to know if there is going to be a button to change between ligth and dark theme or how it will be inplemented.

Thanks for all the help and have a good day,

**Comment by MortenHofft** [comment]
It isn't a theme really. It is simply css overwrites that @javiesgm (who will be happy to hear you like it) has added.
https://github.com/gbif/hp-demo-nhc-dark/blob/master/_sass/_main.scss

Similar to how you have added a bunch of custom css already. 
https://github.com/gbif/hp-colombian-biodiversity/blob/master/_sass/_main.scss

So you can add that today if you want to.

**Comment by MortenHofft** [comment]
I'm closing this, let me know if you believe it should be reopened
