### ISSUE TITLE
Help!!! Broken redirection

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#40]
Hi @MattBlissett!

Early this year you helped us to redirect this IP [http://51.38.48.143:4000/login/](http://51.38.48.143:4000/certifies/) to [biodiversidad.co/certificados/publicacion-permisos](http://biodiversidad.co/certificados/publicacion-permisos) - #34 .

Friday we updated our servers and the above redirection was lost, probably due to a proxy error, our IT contractor @jag2kn asks if you could please restart the server or reload the configuration of that server so it takes the reverse proxy again.

We will deeply appreciate your help with this issue as this tool is key for compliance the environmental norms of the country.

Thank you in advance.

cc @RicardoOrtizG

**Comment by camiplata** [comment]
It is now working! https://biodiversidad.co/certificados/publicacion-permisos/login/?next=/

**Comment by MattBlissett** [comment]
Hi,

I didn't change anything (the emails came at 01:28, 4:37 and 5:17 Copenhagen time).

If there's anything not quite right, please let me know.
