### ISSUE TITLE
Plantillas extensiones no descargan

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#43]
Hola! Estaba revisando https://biodiversidad.co/recursos/plantillas-dwc/#extensiones
y las siguientes plantillas de extensiones me generan un error 403:

[Preservación GGBN](https://drive.google.com/uc?id=1WdH_Lw13a-pg4Teks624pbkqcC1Pr38U&authuser=2&export=download)
[Descripción del Taxón](https://drive.google.com/uc?id=14nwc8BAj1hy-hhI4WB61gmGBfoi_6tjS&authuser=2&export=download)
[Relación del Recurso](https://drive.google.com/uc?id=1JrjJCST859GsKWqsDQCL3GxkGUdbR1I1&authuser=2&export=download)
[Muestra del Material GGBN](https://drive.google.com/uc?id=1g_--FheTtpWIFfsclKmnA6LTDfBzpvAJ&authuser=2&export=download)

No se si es por mi IP o si en efecto están dañados los enlaces, las otras plantillas me descargan sin problema.

<img width="856" alt="Captura de pantalla 2024-06-07 a la(s) 3 31 58 p m" src="https://github.com/gbif/hp-colombian-biodiversity/assets/5700527/526f03a1-7c0b-4fb8-a6a3-d59f4fb5b7cc">

**Comment by EstebanMH-SiB** [comment]
Hola Cami, era por un tema de permisos para la descarga de usuarios externos. En teoría ya quedó y las podrías descargar, pero quedo atento a que me confirmes para cerrar el issue

**Comment by camiplata** [comment]
Gracias Esteban, confirmo que ya funciona ;)
