### ISSUE TITLE
Header color gets lost in small windows

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#9]
Hi @MortenHofft, I want to let you know about the behavior of the header. Dou you think it can be fixed on the template or we rather avoid dark colour headers?

When the window size is reduced more than half or in a table or cellphone the header color gets lost and so does the logo as we are using a white logo with a dark header

How looks in a full window size in a laptop:

<img width="1777" alt="Captura de Pantalla 2021-03-08 a la(s) 9 14 12 a  m" src="https://user-images.githubusercontent.com/5700527/110333528-a9f13280-7fef-11eb-86f9-1d6ff2b9b19f.png">

How looks in a reduce window (less than half of the size) in a laptop:

<img width="893" alt="Captura de Pantalla 2021-03-08 a la(s) 9 14 26 a  m" src="https://user-images.githubusercontent.com/5700527/110333534-ac538c80-7fef-11eb-945e-3115d0c77635.png">

How it looks on an Iphone 6:

![índice](https://user-images.githubusercontent.com/5700527/110333541-ae1d5000-7fef-11eb-8e52-c0ca60af58e9.jpg)

**Comment by MortenHofft** [comment]
Good point - for some reason I just decided that the navbar should always be white on smaller devices. I do not believe I had any good reason for that decision honestly. And I definitely hadn't thought of the logo color.

**Comment by camiplata** [comment]
Great! Then we will keep the dark header with a white logo.
